apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa
spec:
  selector:
    matchLabels:
      run: aa
  replicas: 2
  template:
    metadata:
      labels:
        run: aa
    spec:
      containers:
        - image: busybox
          name: aa
          command:
            - /bin/sh
            - -c
            - "sleep 360835;"
          resources: { }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: new-config-pod
data:
  key1: value1